---
- name: deploy vsftpd
  hosts: all
  gather_facts: no
  tasks:
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: 
        name: vsftpd 
        enabled: true 
        state: restarted
  - name: create readme file
    copy:
                content: "wat moet je hier\n"
                dest: /var/ftp/pub/README
                force: no
                mode: 0444
  - name: add firewall services
    firewalld:
                service: ftp
                state: enabled
                permanent: true
...
