---
  -
    hosts: lamp
    tasks:
      -
        name: include lamp tasks
        include: tasks/lamp.yml
  -
    hosts: file
    tasks:
      -
        name: include file tasks
        include: tasks/file.yml
